### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by srenatus** [bvisness/spall-go#1]
Heya! This is a nice little project, and I'd love to make use of it for testing out Spall from our application code.

But... I can't without a license on this code... would you mind adding one? 😅 

Thanks! :)

**Comment by bvisness** [comment]
Oh, I didn't realize I forgot one! I've added an MIT license. Thanks for pointing that out. Disclaimer though, this project is not very mature, at all, and I dunno if it's even kept up with changes to the spall binary format.

**Comment by srenatus** [comment]
Thanks for the quick response!
